---
- name: Download zabbix_agent2.zip
  ansible.windows.win_get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/6.0/6.0.15/zabbix_agent2-6.0.15-windows-amd64-openssl-static.zip
    dest: C:\Users\{{ ansible_user_id }}\Downloads\zabbix_agent2.zip

- name: Decompress files in zabbix_agent2.zip
  community.windows.win_unzip:
    src: C:\Users\{{ ansible_user_id }}\Downloads\zabbix_agent2.zip
    dest: C:\zabbix
    # delete_archive: yes

- name: Replace zabbix_server and hostname
  ansible.windows.win_template:
    src: ../templates/zabbix_agent2.conf.j2
    dest: C:\zabbix\conf\zabbix_agent2.conf

- name: Install Zabbix Agent2
  ansible.windows.win_powershell:
    script: |
      C:\zabbix\bin\zabbix_agent2.exe --config C:\zabbix\conf\zabbix_agent2.conf --install

- name: Start Zabbix Agent2
  ansible.windows.win_powershell:
    script: |
      C:\zabbix\bin\zabbix_agent2.exe --config C:\zabbix\conf\zabbix_agent2.conf --start
