---
- name: Stop service
  win_service:
    name: Zabbix Agent
    state: stopped

- name: Uninstall Zabbix Agent
  ansible.windows.win_powershell:
    script: |
      C:\Program Files\Zabbix Agent\zabbix_agent2.exe --config C:\Program Files\Zabbix Agent\zabbix_agentd.conf --uninstall
